# Generated by Django 5.1.6 on 2025-03-15 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default='News around the world', validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
