# Generated by Django 5.1.6 on 2025-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Tel-Aviv', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Israel', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0555555555', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default='somewhere', max_length=255),
        ),
    ]
