# Generated by Django 5.1.6 on 2025-03-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
