# Generated by Django 5.1.6 on 2025-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./img/pp_user.jpeg', null=True, upload_to='profile_pic'),
        ),
    ]
